---

- name: Restart pihole_lighttpd
  systemd:
    name: lighttpd
    state: restarted

- name: Restart pihole_exporter
  systemd:
    name: pihole_exporter
    state: restarted

- name: remove list
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pihole_config_path }}/migration_backup/"
    - "{{ pihole_config_path }}/gravity.db"

- name: Update lists
  command: pihole -g
